### ISSUE TITLE
conflicting module name.

### ISSUE THREAD

**Issue by haibeey** [rpip/paystack-go#11]
When i run go get "github.com/rpip/paystack-go" i get the following error.

 `go: github.com/rpip/paystack-go upgrade => v0.0.0-20210424223323-2b8a91696244
go get: github.com/rpip/paystack-go@v0.0.0-20210424223323-2b8a91696244: parsing go.mod:
        module declares its path as: github.com/Obayanju/paystack-go
                but was required as: github.com/rpip/paystack-go`

**Comment by elvis-chuks** [comment]
the go.mod file has a conflicting module name

**Comment by metaclips** [comment]
An alternative fix is to place this at the bottom of your go.mod
```
replace github.com/Obayanju/paystack-go => github.com/rpip/paystack-go v0.0.0-20210424223323-2b8a91696244
```

**Comment by Obayanju** [comment]
This has been fixed in this PR https://github.com/rpip/paystack-go/pull/12
